theme: jekyll-theme-minimal
title: vnx-grid
description: ["In Polymer 2 there is the chance to manage grid with the help of some layouts, but if you feel as I did about managing several grid capabilities at the same time, then try vnx-grid, a simple grid system based on the CSS grid capabilities that let you to experiment with fr metrics, check https://developer.mozilla.org/es/docs/Web/CSS/CSS_Grid_Layout  for more topics related"]
logo: ["main-product.jpg"]
show_downloads: true
